// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// code.cpp
doubles_matrix<> invert_matrix_(doubles_matrix<> A);
extern "C" SEXP _cpp11gaussjordan_invert_matrix_(SEXP A) {
  BEGIN_CPP11
    return cpp11::as_sexp(invert_matrix_(cpp11::as_cpp<cpp11::decay_t<doubles_matrix<>>>(A)));
  END_CPP11
}
// code.cpp
doubles_matrix<> solve_system_(doubles_matrix<> A, doubles_matrix<> b);
extern "C" SEXP _cpp11gaussjordan_solve_system_(SEXP A, SEXP b) {
  BEGIN_CPP11
    return cpp11::as_sexp(solve_system_(cpp11::as_cpp<cpp11::decay_t<doubles_matrix<>>>(A), cpp11::as_cpp<cpp11::decay_t<doubles_matrix<>>>(b)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_cpp11gaussjordan_invert_matrix_", (DL_FUNC) &_cpp11gaussjordan_invert_matrix_, 1},
    {"_cpp11gaussjordan_solve_system_",  (DL_FUNC) &_cpp11gaussjordan_solve_system_,  2},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_cpp11gaussjordan(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
