// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// code.cpp
list squared_unnamed_(doubles x);
extern "C" SEXP _cpp11omp_squared_unnamed_(SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(squared_unnamed_(cpp11::as_cpp<cpp11::decay_t<doubles>>(x)));
  END_CPP11
}
// code.cpp
list squared_named_(doubles x);
extern "C" SEXP _cpp11omp_squared_named_(SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(squared_named_(cpp11::as_cpp<cpp11::decay_t<doubles>>(x)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_cpp11omp_squared_named_",   (DL_FUNC) &_cpp11omp_squared_named_,   1},
    {"_cpp11omp_squared_unnamed_", (DL_FUNC) &_cpp11omp_squared_unnamed_, 1},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_cpp11omp(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
