// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// code.cpp
void cpp11_simplex_phase2_(doubles c, doubles b, doubles_matrix<> A);
extern "C" SEXP _cpp11simplexphase2_cpp11_simplex_phase2_(SEXP c, SEXP b, SEXP A) {
  BEGIN_CPP11
    cpp11_simplex_phase2_(cpp11::as_cpp<cpp11::decay_t<doubles>>(c), cpp11::as_cpp<cpp11::decay_t<doubles>>(b), cpp11::as_cpp<cpp11::decay_t<doubles_matrix<>>>(A));
    return R_NilValue;
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_cpp11simplexphase2_cpp11_simplex_phase2_", (DL_FUNC) &_cpp11simplexphase2_cpp11_simplex_phase2_, 3},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_cpp11simplexphase2(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
