# Generated by cpp11: do not edit by hand

invert_matrix_ <- function(A) {
  .Call(`_cpp11gaussjordan_invert_matrix_`, A)
}

solve_system_ <- function(A, b) {
  .Call(`_cpp11gaussjordan_solve_system_`, A, b)
}
