# Generated by cpp11: do not edit by hand

one_cpp_ <- function() {
  .Call(`_ece244_one_cpp_`)
}

sign_cpp_ <- function(x) {
  .Call(`_ece244_sign_cpp_`, x)
}

sum_cpp_ <- function(x) {
  .Call(`_ece244_sum_cpp_`, x)
}

mean_cpp_ <- function(x) {
  .Call(`_ece244_mean_cpp_`, x)
}

var_cpp_ <- function(x) {
  .Call(`_ece244_var_cpp_`, x)
}

rmse_cpp_ <- function(x, x0) {
  .Call(`_ece244_rmse_cpp_`, x, x0)
}

cumsum_cpp_ <- function(x) {
  .Call(`_ece244_cumsum_cpp_`, x)
}

any_cpp_ <- function(x) {
  .Call(`_ece244_any_cpp_`, x)
}

which_cpp_ <- function(pred, x) {
  .Call(`_ece244_which_cpp_`, pred, x)
}

all_cpp_4_ <- function(x) {
  .Call(`_ece244_all_cpp_4_`, x)
}

all_cpp_3_ <- function(x) {
  .Call(`_ece244_all_cpp_3_`, x)
}

all_cpp_2_ <- function(x) {
  .Call(`_ece244_all_cpp_2_`, x)
}

all_cpp_1_ <- function(x) {
  .Call(`_ece244_all_cpp_1_`, x)
}

cumprod_cpp_ <- function(x) {
  .Call(`_ece244_cumprod_cpp_`, x)
}

cumprod_cpp_2_ <- function(x) {
  .Call(`_ece244_cumprod_cpp_2_`, x)
}

cummin_cpp_ <- function(x) {
  .Call(`_ece244_cummin_cpp_`, x)
}

cummax_cpp_ <- function(x) {
  .Call(`_ece244_cummax_cpp_`, x)
}

diff1_cpp_ <- function(x) {
  .Call(`_ece244_diff1_cpp_`, x)
}

diff_cpp_ <- function(x, lag) {
  .Call(`_ece244_diff_cpp_`, x, lag)
}

range_cpp_ <- function(x) {
  .Call(`_ece244_range_cpp_`, x)
}

sum2_cpp_ <- function(x, na_rm) {
  .Call(`_ece244_sum2_cpp_`, x, na_rm)
}

mean2_cpp_ <- function(x, na_rm) {
  .Call(`_ece244_mean2_cpp_`, x, na_rm)
}

var2_cpp_ <- function(x, na_rm) {
  .Call(`_ece244_var2_cpp_`, x, na_rm)
}

rmse2_cpp_ <- function(x, x0, na_rm) {
  .Call(`_ece244_rmse2_cpp_`, x, x0, na_rm)
}

cumsum2_cpp_ <- function(x, na_rm) {
  .Call(`_ece244_cumsum2_cpp_`, x, na_rm)
}

cumprod2_cpp_ <- function(x, na_rm) {
  .Call(`_ece244_cumprod2_cpp_`, x, na_rm)
}

cummin2_cpp_ <- function(x, na_rm) {
  .Call(`_ece244_cummin2_cpp_`, x, na_rm)
}

cummax2_cpp_ <- function(x, na_rm) {
  .Call(`_ece244_cummax2_cpp_`, x, na_rm)
}
